# Generated by Django 2.2.3 on 2019-07-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=50, unique=bool)),
                ('name', models.CharField(max_length=20)),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
    ]
