# Generated by Django 2.2.3 on 2019-07-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'view_news_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordAll',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('times', models.IntegerField()),
            ],
            options={
                'db_table': 'view_amount_of_keyword_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordToday',
            fields=[
                ('keyword', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('times', models.IntegerField()),
            ],
            options={
                'db_table': 'view_amount_of_keyword_today',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('keyword', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
    ]
