# Generated by Django 2.2.3 on 2019-07-31 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapnews', '0002_delete_channel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
