# Generated by Django 2.2.3 on 2019-07-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapnews', '0003_delete_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
