# Generated by Django 2.2.4 on 2019-08-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapnews', '0005_record_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user_id',
            new_name='user',
        ),
    ]
