# Generated by Django 2.2.4 on 2019-08-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snapnews', '0006_auto_20190806_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeywordAll',
        ),
        migrations.DeleteModel(
            name='KeywordToday',
        ),
    ]
