# Generated by Django 2.2.3 on 2019-07-26 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(blank=True, max_length=128, verbose_name='Organization')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('line_api_key', models.CharField(blank=True, max_length=100, verbose_name='LINE api key')),
                ('email_address', models.CharField(blank=True, max_length=100, verbose_name='Email address')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_group', models.CharField(max_length=30)),
                ('keyword_included', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10)),
                ('keyword_excluded', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=210, size=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Keyword',
            },
        ),
    ]
