# Generated by Django 2.2.4 on 2019-08-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_auto_20190731_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeyword',
            name='keyword',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
